### ISSUE TITLE
Create tests for KeyboardBinder

### ISSUE THREAD

**Issue by Empiree** [Empiree/DeftSharp.Windows.Input#12]
Write KeyboardBinder tests in the DeftSharp.Windows.Input.Tests.Keyboard namespace. Feel free to try something new, you don't have to do everything according to other tests. But if you don't have any ideas, you can look at how other tests are implemented.

**Comment by tmezups** [comment]
Hello!
I would like to tackle this issue if I may?

**Comment by Empiree** [comment]
> Hello! I would like to tackle this issue if I may?
Hey! Yeah, this is going to be awesome. Feel free to contribute

**Comment by Empiree** [comment]
**Thank you for your contribution!** 

If you have the desire, you can take one of these challenges: 
[Create a LetterListener class](https://github.com/Empiree/DeftSharp.Windows.Input/issues/6)
[Create a NumberListener class](https://github.com/Empiree/DeftSharp.Windows.Input/issues/5)
[Swap() method for KeyboardBinder](https://github.com/Empiree/DeftSharp.Windows.Input/issues/17)

Or if you get any new ideas, be sure to post them!

I would be very pleased if you could put a star on the repository :)

Have a good day!
