### ISSUE TITLE
Create tests for MouseManipulator

### ISSUE THREAD

**Issue by Empiree** [Empiree/DeftSharp.Windows.Input#22]
Write MouseManipulator tests in the DeftSharp.Windows.Input.Tests.Mouse namespace. 

Please maintain consistency and pay attention to the code-style of other tests. But at the same time, don't hesitate to try something new.

**Comment by jordonkane** [comment]
Hey @Empiree !

Cool project you've got there. Been looking at it for a few hours. I'll add some tests for you similar to the KeyboardManipulatorTests class :)

**Comment by Empiree** [comment]
Hi @jordonkane !

Thank you, I'm glad to hear you enjoyed the library! :) 

Your contribution would be very helpful! Since there is little coverage of the library with tests, the current focus is on implementing functionality.

**Comment by Empiree** [comment]
Closed by https://github.com/Empiree/DeftSharp.Windows.Input/pull/41
