### ISSUE TITLE
Create tests for Sequences

### ISSUE THREAD

**Issue by Empiree** [Empiree/DeftSharp.Windows.Input#24]
Write KeyboardListener tests for: 

- SubscribeSequence
- SubscribeSequenceOnce
- Unsubscribe (Sequence)

Place it in the DeftSharp.Windows.Input.Tests.Keyboard namespace.

Please maintain consistency and pay attention to the code-style of other tests. But at the same time, don't hesitate to try something new.

**Comment by michLukaszewicz** [comment]
Assign me for that, please!

**Comment by Empiree** [comment]
Closed by https://github.com/Empiree/DeftSharp.Windows.Input/pull/31 (Added Tests for Sequence subscribe and unsubscribe)
