### ISSUE TITLE
Create tests for Combinations

### ISSUE THREAD

**Issue by Empiree** [Empiree/DeftSharp.Windows.Input#25]
Write KeyboardListener tests for: 

- SubscribeCombination
- SubscribeCombinationOnce
- Unsubscribe (Combination)

Place it in the DeftSharp.Windows.Input.Tests.Keyboard namespace.

Please maintain consistency and pay attention to the code-style of other tests. But at the same time, don't hesitate to try something new.

**Comment by michLukaszewicz** [comment]
Hello, could I grab it?

**Comment by Empiree** [comment]
Hey @michLukaszewicz , yeah. That would be awesome!

**Comment by Empiree** [comment]
Closed by https://github.com/Empiree/DeftSharp.Windows.Input/pull/27 (Added tests for Combination subscribe and unsubscribe)
