### ISSUE TITLE
Custom Interceptors

### ISSUE THREAD

**Issue by Empiree** [Empiree/DeftSharp.Windows.Input#30]
I would like to discuss one of the ideas for future releases. 

This idea consists in creating a custom interceptor, the logic of which can be described in a class, for example, inheriting from `CustomKeyboardInterceptor`.

The logic is as follows: before any button press is processed, we pass through registered interceptors such as KeyboardListener, KeyboardManipulator, etc. If at least 1 interceptor does not allow processing of the press, it will not be processed anywhere and the OnPipelineFailed method will be called, if all interceptors allow processing of the key, the OnPipelineSuccess method will be called. 

So, I'm thinking of making it possible for the user to create custom interceptors that will be registered with all other interceptors in one pipeline. This would allow the user to decide and define the processing logic. But this way is a bit more complicated than usual, so I want to focus on convenient methods, and leave this option as the last one.

Here is an example of one such class:

![image](https://github.com/Empiree/DeftSharp.Windows.Input/assets/60399216/c4bcffee-acb1-4fd5-b1c8-91d2ab9036b0)

How do you feel about that?

**Comment by Empiree** [comment]
An example of a simple keyboard logger.

![image](https://github.com/Empiree/DeftSharp.Windows.Input/assets/60399216/8ef79430-ea8d-4ec7-8cd4-162f5d85be7e)

**Comment by nullptrException100** [comment]
Yes, it looks very useful in certain scenarios. Ideally, make 95% of all needs covered by already written interceptors, like `KeyboardListener`. But in the case where that's not enough, this way could make it much easier to implement.

**I support this idea.**

**Comment by Empiree** [comment]
Added in 0.6 release! [Changelog](https://github.com/Empiree/DeftSharp.Windows.Input/releases/tag/v0.6)

**Comment by AlexanderBlackman** [comment]
> Added in 0.6 release! [Changelog](https://github.com/Empiree/DeftSharp.Windows.Input/releases/tag/v0.6)

Excellent! You solve problems so quickly.
