### ISSUE TITLE
Improve the NumpadListener class

### ISSUE THREAD

**Issue by Empiree** [Empiree/DeftSharp.Windows.Input#39]
Currently, the [NumpadListener](https://github.com/Empiree/DeftSharp.Windows.Input/blob/main/DOCUMENTATION.md#numpadlistener) class only takes one `Action<Key>` argument when subscribing. It would be great to extend its functionality, and add optional parameters that exist in the `Subscribe()` methods in the [KeyboardListener](https://github.com/Empiree/DeftSharp.Windows.Input/blob/main/DOCUMENTATION.md#keyboardlistener) class. 

1. A `TimeSpan` parameter that will accept the delegate trigger interval. 
2. A `KeyboardEvent` parameter that will accept the event type.

Also, you can think how to improve this class. Feel free to suggest your ideas!

**I will be glad to answer all your questions!**

**Comment by jo3stevens** [comment]
Hey @Empiree 

I'm doing a code contribution as part of a job interview process and came across your project. I'm happy to pick up this enhancement.

Cheers

**Comment by Empiree** [comment]
Hi @jo3stevens ! 

Contributing to an open-source project is always cool. I'm glad you paid attention to this library :)

I'll do a review of your PR shortly. I would also be very happy if you put a star on this repository to promote it. 

Have a nice day!
