### ISSUE TITLE
Create a NumberListener class

### ISSUE THREAD

**Issue by Empiree** [Empiree/DeftSharp.Windows.Input#5]
This class will handle pressing any digits on the keyboard. Follow the [NumpadListener](https://github.com/Empiree/DeftSharp.Windows.Input/blob/main/DOCUMENTATION.md#numpadlistener) example. 

The class must contain a `Subscribe` method that will accept `Action<Key>` and will subscribe to all possible number buttons, including NumPad. 

And it must also contain an `Unsubscribe` method to unsubscribe from all keyboard events. 

Important! Use `GUID` to unsubscribe only those subscriptions that we have created inside this class.

**Comment by romadanskiy** [comment]
@Empiree u can assign this issue to me :)

**Comment by Empiree** [comment]
Hi @romadanskiy !

Are you still interested in this issue?

**Comment by Empiree** [comment]
> @Empiree Yes, I am 😅 I'll open PR this weekend. Sorry for the wait.

It's all good! You can take your time, I just wanted to see if maybe you changed your plans and I should put this issue as open. Thank you and have a good day! :)

**Comment by Empiree** [comment]
Closed by https://github.com/Empiree/DeftSharp.Windows.Input/pull/44
