### ISSUE TITLE
Create a LetterListener class

### ISSUE THREAD

**Issue by Empiree** [Empiree/DeftSharp.Windows.Input#6]
This class will handle pressing any letters on the keyboard. Follow the [NumpadListener](https://github.com/Empiree/DeftSharp.Windows.Input/blob/main/DOCUMENTATION.md#numpadlistener) example. 

The class must contain a `Subscribe` method that will accept `Action<Key>` and will subscribe to all possible letter buttons.

And it must also contain an `Unsubscribe` method to unsubscribe from all keyboard events. 

Important! Use `GUID` to unsubscribe only those subscriptions that we have created inside this class.

**Comment by PaezFrancisco** [comment]
Hello @Empiree!
I'm Francisco, pursuing my degree in Systems Engineering at college.I would love to lend a hand and contribute to resolving this issue by developing this class. Please feel free to let me know if you're on board with that and if there's anything specific you need from my end to assist you further.

Wishing you a blessed day!

**Comment by Empiree** [comment]
@PaezFrancisco 

Hi Francisco! I'm glad you're interested in this project and ready to help in its development! :)

Basically, the task is to create a new LetterListener class based on the example of NumpadListener. But unlike it, we have to take into account the variety of keyboards and their layouts in order to subscribe to all available buttons. It would be nice to also write xUnit tests to this class.

Also, in addition to implementing this task, you can think about what other similar classes could be created, or how to extend existing ones. 

If you have any questions, I'm happy to answer them!

**Comment by PaezFrancisco** [comment]
@Empiree 
Thank you for your swift response! I'll keep you updated on my progress in the coming days. Have a wonderful and blessed day!

**Comment by Empiree** [comment]
> @Empiree Thank you for your swift response! I'll keep you updated on my progress in the coming days. Have a wonderful and blessed day!

Thanks, wishing you a great day too! :)

**Comment by PaezFrancisco** [comment]
Hi @Empiree ! Hope you are having a great day! 
I've made some progress on the development, taking cues from the NumpadListener class. However, I have a question regarding how many keyboard layouts you'd like to include. Currently, I've focused on the most common ones, namely QWERTY layouts in English and Spanish (refer to the first attached image).
![Imagen de WhatsApp 2024-05-04 a las 19 48 56_164f2f57](https://github.com/Empiree/DeftSharp.Windows.Input/assets/85041279/8ef8d32b-4026-48b1-a063-9c549cfd15d3)


While I'm eager to expand to other layouts, the sheer number of keyboard distributions out there could make this search quite extensive. To streamline the process and ensure we cover the most relevant options, could you please provide guidance on which other distributions you'd like me to include?

Thank you for your input!

**Comment by Empiree** [comment]
Hi, @PaezFrancisco !

I think we should start by focusing on the most popular QWERTY layouts. We can also add [AZERTY](https://en.wikipedia.org/wiki/AZERTY) (French layout), in the future we can extend the functionality of this class and add something new.

**Comment by PaezFrancisco** [comment]
Great! 
I will add AZERTY with french layout.
I will be starting the test this week.
Thanks for your quick response @Empiree !

**Comment by PaezFrancisco** [comment]
Hi @Empiree ! Hope you are having a great day! Regarding this issue, i have succesfully created the class and the classes for the test, all tho, i am facing issues while runing the DeftSharp.Windows.Input.Tests.csproj. 
This is the error i am facing: "**_Unhandled exception of type 'System.IO.FileNotFoundException' in Unknown Module.
Cannot load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the specified file._**"

I am using this version of .NET: 7.0.100 [C:\Program Files\dotnet\sdk].
Have you ever faced the same issue? Or have any idea how can i solve it? 
Thanks in advance

**Comment by Empiree** [comment]
Hi @PaezFrancisco ! 

This is a very strange issue, since the code does not use file handling anywhere and I and other developers have not encountered this. Therefore, it seems to me that the whole problem is with the local build of the project. Try to clean up the build and do a rebuild.

Is your WPF.Playground project working ? 

Also, I suggest pulling up the new changes in the project to work with the current codebase. The project moved to .NET 8 a couple weeks ago, maybe that will help solve the problem.

**Comment by PaezFrancisco** [comment]
Hi @Empiree ! Pull Requests its created, please review it and let me know if there is any doubts.Thanks
